services:
  web:
    depends_on:
      - storage
      - api

    build: ./paza-frontend

    ports:
      - "3000:3000"

    environment:
      - api_url=http://localhost:8000

    develop:
      watch:
        - action: rebuild
          path: ./paza-frontend/package.json
        - action: rebuild
          path: ./paza-frontend/package-lock.json

        - action: sync
          path: ./paza-frontend
          target: /app

  storage:
    build: ./paza-storage

    ports:
      - "2500:2500"
    env_file:
      - ./paza-storage/.env

    environment:
      - storage_url=http://localhost:2500

  api:
    build: ./paza-backend

    ports:
      - "5050:5050"
    env_file:
      - ./paza-backend/.env

    develop:
      watch:
        - action: rebuild
          path: ./paza-backend/package.json
        - action: rebuild
          path: ./paza-backend/package-lock.json
        - action: sync
          path: ./paza-backend
          target: /app
